[package]
name = "xml-orange"
version = "0.1.0"
authors = ["Chris Neidhart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
